# Pandas

## Import

In [1]:
import pandas as pd

## Series

In [2]:
a = [1 ,7, 2]
var = pd.Series(a)
print(var)

0    1
1    7
2    2
dtype: int64

In [4]:
var = pd.Series({"1":"test", "2":"test2", "3":"test3"})
print(var)

1     test
2    test2
3    test3
dtype: object

## Dataframe

In [5]:
data = {
    "calories": [230, 420, 390],
    "duration": [45, 56, 80]
}

data = pd.DataFrame(data)
print(data)

   calories  duration
0       230        45
1       420        56
2       390        80

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   calories  3 non-null      int64
 1   duration  3 non-null      int64
dtypes: int64(2)
memory usage: 176.0 bytes

In [7]:
data.describe()

         calories   duration
count    3.000000   3.000000
mean   346.666667  60.333333
std    102.143690  17.897858
min    230.000000  45.000000
25%    310.000000  50.500000
50%    390.000000  56.000000
75%    405.000000  68.000000
max    420.000000  80.000000

In [8]:
data.head()

   calories  duration
0       230        45
1       420        56
2       390        80

In [15]:
print(data.loc[0], data.loc[1], sep='\n\n')

calories    230
duration     45
Name: 0, dtype: int64

calories    420
duration     56
Name: 1, dtype: int64

## Read From CSV

In [16]:
!wget https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv

--2023-07-05 15:29:11--  https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3975 (3.9K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   3.88K  --.-KB/s    in 0s

2023-07-05 15:29:11 (50.7 MB/s) - ‘iris.csv’ saved [3975/3975]

In [17]:
!ls

iris.csv  sample_data

In [19]:
df = pd.read_csv('iris.csv')

In [20]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [23]:
df.tail()

     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [21]:
df.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [24]:
# correlations
df.corr()

<ipython-input-24-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

              sepal.length  sepal.width  petal.length  petal.width
sepal.length      1.000000    -0.117570      0.871754     0.817941
sepal.width      -0.117570     1.000000     -0.428440    -0.366126
petal.length      0.871754    -0.428440      1.000000     0.962865
petal.width       0.817941    -0.366126      0.962865     1.000000